### ISSUE TITLE
SBML Version Support Documentation

### ISSUE THREAD

**Issue by nanowizard** [draeger-lab/SBSCL#29]
First I'll just mention that this library is awesome! Thank you for all your hard work on it. We're currently using it to simulate patient physiology in a branch of our [synthetic patient generator](https://github.com/synthetichealth/synthea/tree/physiology) which will hopefully get pulled into a release in the near future.

So, to the issue at hand:

It would be helpful to know which version of the SBML specification this library supports.

I just attempted to use the `min` and `max` operators which appear to have been added in the current version of the [SBML spec (level 3 version 2, section 3.4.1)](http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf). What surprised me is that the simulation ran without errors, but the output table had `NaN` values for parameters assigned with `min` and `max` operators in the equations. We can workaround this issue by using `piecewise` elements, but it would have been nice to know beforehand that the library wouldn't handle `max` and `min` properly.

Of course, this is all assuming that the current release of SBSCL doesn't support SBML level 3 version 2. If it _is_ supposed to support those functions, then consider this a bug report as well :).

The docs mention which version of the SBML test suite the library is evaluated against, but doesn't mention anything about which versions of the spec are supported. I recommend adding this information to the docs and the README.

**Comment by shalinshah1993** [comment]
This seems to be something that can be added in JSBML rather than SBSCL. Perhaps, @draeger can comment more on that.

**Comment by nanowizard** [comment]
@shalinshah1993 good point about JSBML though I think it would be nice to have it documented for both.

**Comment by draeger** [comment]
@nanowizard thank you for your feedback! When the library was implemented, we made sure to support all levels and versions of SBML that were available at that time (see the [publication](http://dx.doi.org/10.1186/1752-0509-7-55)).

During the Google Summer of Code in 2018 we worked mainly on supporting [SED-ML](http://sed-ml.org) and the extension for [flux balance analysis](http://sbml.org/specifications/sbml-level-3/version-1/fbc/sbml-fbc-version-2-release-1.pdf), as well as updating the library itself, but we did not yet implement newer features that came along with [SBML Level 3 Version 2](https://doi.org/10.1515/jib-2019-0021).

There is a new [Google Summer of Code](https://github.com/nrnb/GoogleSummerOfCode/issues/141) project that we planned. This project would allow us to implement the missing features you describe and to update the library to the latest versions of SBML.
