### ISSUE TITLE
Travis tests are currently failing

### ISSUE THREAD

**Issue by matthiaskoenig** [draeger-lab/SBSCL#34]
Currently the tests are failing
https://github.com/draeger-lab/SBSCL/commits/master
https://travis-ci.com/github/draeger-lab/SBSCL/builds/154929373

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, I updated the JDK in my forked repo of SBSCL and the build still fails and that is due to some issues in the CompSimulatorTest files which have to be resolved.

My forked repo Travis build:
https://travis-ci.com/github/hemilpanchiwala/SBSCL/builds/165539283

**Comment by matthiaskoenig** [comment]
Did you get the tests locally to run and see the same issue?
You should fix the underlying cause in the CompTests. This is a good chance to get to know the test structures and how the comp simulations work currently.

I.e. get the tests running locally and fix the CompIssues. If you tests pass on your travis make a pull request with the changes so we can review it.

**Comment by hemilpanchiwala** [comment]
Yes, I see the same issues while running the tests locally. Okay, I will fix the comp issues, and once the test pass, I will make a pull request with the changes.

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, this error occurs when two or more parameters or compartments are specified in the SBML files with comp, i.e., from `test6.xml` to `test10.xml`. The error is returned when the flatten method is called on the SBML document in CompSimulator.java.

I don't understand that is this error in the CompFlatteningConverter.java of JSBML?

Error while running test on `src/test/resources/comp/test6.xml`:-
ERROR (Model.java:4687) - An element of type parameter with the id "Mod1subparam2" is already present in this model. The new element of type parameter will not have it's id set. In some cases, the new element will not be added to the model.
<img src="https://i.ibb.co/8xQ4rv3/Screenshot-from-2020-05-13-16-21-31.png" />

**Comment by matthiaskoenig** [comment]
A lot happend in the CompFlatteningConverter in JSBML. We probably have to update JSBML first to the latest version to see if the error still exists in the latest version. 
I.e. fix https://github.com/draeger-lab/SBSCL/issues/32.
You should update JSBML first and see it does not break any other tests. Then see if the Comp errors exist still with the latest JSBML version.

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, I have updated pom.xml to JSBML 1.5

Commit Link:
https://github.com/hemilpanchiwala/SBSCL/commit/ae34768d22aa722fcd48b41550589e2ac9eadaff

**Comment by matthiaskoenig** [comment]
@hemilpanchiwala 
Trying to get this running locally to figure out what is going on.

**Comment by matthiaskoenig** [comment]
I could reproduce the issue and checked that
- models are valid SBML (online validator)
- can be flattened with libsbml-python bindings

This seems to be an issue with the flattening routine and is reported here:
sbmlteam/jsbml#213

Please ignore the CompTests for now, which are tracked in #36. The main issue here is resolved and can be closed.
