### ISSUE TITLE
Add support for rateOf csymbol

### ISSUE THREAD

**Issue by hemilpanchiwala** [draeger-lab/SBSCL#43]
A new `rateOf` csymbol has been introduced to the SBML Level 3 Version 2. Support for `rateOf` needs to be added to SBSCL which can be done by creating a function calculating a rate of any particular variable that needs to be added in the ASTNodeInterpreter class of SBSCL. Currently the SBML L3V2 models containing `rateOf` symbol outputs `NaN` values as results.

**Comment by hemilpanchiwala** [comment]
@draeger @matthiaskoenig, can you once specify how will the rateOf be calculated for the Compartment or Parameter Node?

**Comment by hemilpanchiwala** [comment]
@draeger @matthiaskoenig 
Now, the `rateOf` method has been added to the SBSCL simulator and now many tests with `rateOf` tests are passing now. ([Link](https://github.com/hemilpanchiwala/SBSCL/blob/testrunner/src/main/java/org/simulator/sbml/astnode/ASTNodeInterpreter.java#L1095) to the rateOf method)

However, there is a problem for time `t = 0` in some test cases, as the `rateOf` is called before the derivatives are computed which leads to wrong results and thus failed tests. This occurs for the test cases [1256](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01256/01256-sbml-l3v2.xml), [1257](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01257/01257-sbml-l3v2.xml), and some others.

Screenshot of the results from the SBML Test Runner. (Difference in results is at `t = 0` only)
![Screenshot from 2020-06-15 15-51-31](https://user-images.githubusercontent.com/42446679/84646695-21da7280-af20-11ea-96b4-200b77da416f.png)

**Comment by matthiaskoenig** [comment]
Here some hints for the implmentation:
* `The rateOf for any symbol declared constant is zero!` (i.e. you can check if the compartment or parameter, ... is constant before calculating derivatives
* `rateOf` can be calculated on Compartment, LocalParameter, Parameter, Species, and SpeciesReference 
* If volumes are changing for species in concentrations you need the combined derivative (see SBML specification):
![image](https://user-images.githubusercontent.com/900538/84651824-d5d10300-af0a-11ea-9dfe-b9d42797af02.png)
* You need the derivatives before you calculate the `rateOf`

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, I have implemented this by passing the instance of SBMLinterpreter in the rateOf method and getting the derivatives calculated by computeDerivatives method in SBMLinterpreter. The only problem I get is that at t = 0, the rateOf is calculated even before the derivatives are computed so gets the derivative field null.

**Comment by hemilpanchiwala** [comment]
Here is the implementation: https://github.com/hemilpanchiwala/SBSCL/blob/b73b2931cb7b4d5318ff19076dad1893ee076213/src/main/java/org/simulator/sbml/astnode/ASTNodeInterpreter.java#L1095

**Comment by matthiaskoenig** [comment]
I nowhere see the handling of the constant symbols or the combined derivatives of concentration species?

Also put things outside of loops if you can:
```
for (int i = 0; i < sbmlInterpreter.getRateRulesRoots().size(); i++) {
      if (sbmlInterpreter.getRateRulesRoots().get(i).getVariable().equals(sBase.getId())) {
        return sbmlInterpreter.getRateRulesRoots().get(i).getNodeObject().compileDouble(time, 0d);
      }
    }
```
Here you do in every loop iteration four possibly expensive unnecessary function calls. No sure this is optimized away, but much better to do things outside of loops and remove duplicate calls:
```
rateRulesRoots = sbmlInterpreter.getRateRulesRoots()
for (int i = 0; i < rateRulesRoots.size(); i++) {
     rrRoot = rateRulesRoots.get(i);
      if (rrRoot.getVariable().equals(sBase.getId())) {
        return rrRoot.getNodeObject().compileDouble(time, 0d);
      }
    }
```

**Comment by matthiaskoenig** [comment]
So you have to figure out how to evaluate the derivatives before the rateOfs if rateOfs are in the model.

**Comment by hemilpanchiwala** [comment]
> I nowhere see the handling of the constant symbols or the combined derivatives of concentration species?

@matthiaskoenig, I will add handling for the constant symbols but the species with concentration or amount units are being handled in the computeDerivatives itself in SBMLinterpreter.

**Comment by hemilpanchiwala** [comment]
> I nowhere see the handling of the constant symbols.

Link to the rateOf function: https://github.com/hemilpanchiwala/SBSCL/blob/testrunner/src/main/java/org/simulator/sbml/astnode/ASTNodeInterpreter.java#L1095
@matthiaskoenig, Does this seem okay now or should I make all the if statements for returning 0d in just one if statement?

**Comment by matthiaskoenig** [comment]
Just calculate once the constant base in a hash map and look them up
instead of doing all this tests every integration step.

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, added a constant hashmap in SBMLinterpreter and updated the rateOf method in the linked commit above. Does it seem fine now? 
Updated rateOf method [[Link](https://github.com/hemilpanchiwala/SBSCL/blob/3c680b9495b7a6fda9b410b9bca35d0124ae5ed0/src/main/java/org/simulator/sbml/astnode/ASTNodeInterpreter.java#L1095 )].

**Comment by hemilpanchiwala** [comment]
I also find one test case of rateOf which fails but I don't get any clue for it. Test case [1456](https://github.com/sbmlteam/sbml-test-suite/blob/develop/cases/semantic/01456/01456-sbml-l3v2.xml).
