### ISSUE TITLE
Terminology, Power and Oppressive Language in Computer Science

### ISSUE THREAD

**Issue by draeger** [draeger-lab/SBSCL#52]
To avoid implying any oppressive language, we should rename the `master` branch to `main` by following these recommendations: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by draeger** [comment]
It seems renaming the master branch will cause problems with GitHub pages: https://seankilleen.com/2020/06/how-to-rename-your-default-branch-away-from-master-while-using-github-pages/

**Comment by hemilpanchiwala** [comment]
@draeger, GitHub officially says to wait for its new updates which will seamlessly provide support for changing `master` branch to `main` branch.

Guidelines by GitHub on renaming branch name: https://github.com/github/renaming
