### ISSUE TITLE
Update Maven dependency documentation (version 2.0)

### ISSUE THREAD

**Issue by matthiaskoenig** [draeger-lab/SBSCL#62]
The maven dependency documentation is outdated at
https://draeger-lab.github.io/SBSCL/dependency-info.html
Also the maven and usage dependency information should be stated in the README!. It took me quit some time to find this information starting from the github repository.

**Comment by draeger** [comment]
Solved with https://github.com/draeger-lab/SBSCL/commit/36ba74c422e3e12e7ce5d9c3acfff725f5dafcb4.
