### ISSUE TITLE
Upload SBSCL to mvnrepository

### ISSUE THREAD

**Issue by matthiaskoenig** [draeger-lab/SBSCL#63]
I think SBSCL is not jet on a central maven repository.
https://mvnrepository.com/search?q=sbscl
See for instance JSBML instead
https://mvnrepository.com/search?q=jsbml

We should provide SBSCL via a central maven repository so that it can be easily included in projects.

**Comment by matthiaskoenig** [comment]
See for instance discussion in: https://github.com/TakahiroYamada/SBMLWebApp/issues/1

**Comment by draeger** [comment]
I am on it. Moving SBSCL to Maven Central is on my list. I'll post an update here when it is done.

**Comment by draeger** [comment]
Solved with comm https://github.com/draeger-lab/SBSCL/commit/676766c820ed1f482f189a3fb8618cd84a436023.
